/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.community;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author maqielhm
 */
public class CommunityRows extends javax.swing.JPanel implements ListCellRenderer {

    /**
     * Creates new form CommunityRows
     */
    public CommunityRows() {
        initComponents();
        spCommunityRow.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCommunityRowName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCommunityRowTitle = new javax.swing.JLabel();
        spCommunityRow = new javax.swing.JScrollPane();
        taCommunityRowBody = new javax.swing.JTextArea();
        lblCommunityDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        lblCommunityRowName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCommunityRowName.setText("John Doe");

        jLabel3.setText("Created By");

        lblCommunityRowTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblCommunityRowTitle.setText("Lorem Ipsum Sim Dolor Amet");

        taCommunityRowBody.setEditable(false);
        taCommunityRowBody.setColumns(20);
        taCommunityRowBody.setLineWrap(true);
        taCommunityRowBody.setRows(5);
        taCommunityRowBody.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. \nNam ac tristique nulla. Proin viverra elit quis est \neuismod malesuada. Cras in egestas arcu. . . ");
        taCommunityRowBody.setWrapStyleWord(true);
        taCommunityRowBody.setAutoscrolls(false);
        taCommunityRowBody.setBorder(null);
        taCommunityRowBody.setOpaque(false);
        spCommunityRow.setViewportView(taCommunityRowBody);

        lblCommunityDate.setText("Thursday, 11 August 2018");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCommunityRowName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCommunityDate)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCommunityRowTitle)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spCommunityRow, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCommunityRowTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCommunityRow, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunityDate)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCommunityRowName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCommunityDate;
    private javax.swing.JLabel lblCommunityRowName;
    private javax.swing.JLabel lblCommunityRowTitle;
    private javax.swing.JScrollPane spCommunityRow;
    private javax.swing.JTextArea taCommunityRowBody;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        CommunityModel model = (CommunityModel) value;
        lblCommunityDate.setText(model.getDate());
        lblCommunityRowName.setText(model.getName());
        lblCommunityRowTitle.setText(model.getTitle());
        taCommunityRowBody.setText(model.getBody());
        return this;
    }
}
