/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.member;

import home.community.*;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author maqielhm
 */
public class MemberRowView extends javax.swing.JPanel implements ListCellRenderer {

    /**
     * Creates new form CommunityRows
     */
    public MemberRowView() {
        initComponents();
        setOpaque(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblMemberRowPicture = new javax.swing.JLabel();
        lblMemberRowName = new javax.swing.JLabel();
        lblMemberRowPosition = new javax.swing.JLabel();
        lblMemberRowComm = new javax.swing.JLabel();
        lblMemberRowTitle = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblMemberRowNumPost = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblMemberRowStatus = new javax.swing.JLabel();

        setBorder(null);
        setOpaque(false);

        lblMemberRowPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/ic_account_circle.png"))); // NOI18N
        lblMemberRowPicture.setText("jLabel16");

        lblMemberRowName.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblMemberRowName.setText("M Aqiel Hilman");

        lblMemberRowPosition.setText("Veteran at");

        lblMemberRowComm.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblMemberRowComm.setText("Community Name");

        lblMemberRowTitle.setText("Title");

        jLabel20.setText("Post :");

        lblMemberRowNumPost.setText("Num");

        jLabel21.setText("Status : ");

        lblMemberRowStatus.setText("Offline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMemberRowPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberRowName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMemberRowPosition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMemberRowComm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMemberRowTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMemberRowNumPost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMemberRowStatus)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemberRowPicture)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMemberRowName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMemberRowPosition)
                            .addComponent(lblMemberRowComm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMemberRowTitle)
                            .addComponent(jLabel20)
                            .addComponent(lblMemberRowNumPost)
                            .addComponent(jLabel21)
                            .addComponent(lblMemberRowStatus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMemberRowComm;
    private javax.swing.JLabel lblMemberRowName;
    private javax.swing.JLabel lblMemberRowNumPost;
    private javax.swing.JLabel lblMemberRowPicture;
    private javax.swing.JLabel lblMemberRowPosition;
    private javax.swing.JLabel lblMemberRowStatus;
    private javax.swing.JLabel lblMemberRowTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        MemberRowModel model = (MemberRowModel) value;
        lblMemberRowComm.setText(model.getCommunityName());
        lblMemberRowName.setText(model.getName());
        lblMemberRowNumPost.setText(model.getNumberPost());
        lblMemberRowPosition.setText(model.getCommunityPosition());
        lblMemberRowStatus.setText(model.getStatus());
        lblMemberRowTitle.setText(model.getTitle());
        
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        return this;
    }
}
