/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.com_thread;

import home.community.*;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author maqielhm
 */
public class CommunityThreadRowView extends javax.swing.JPanel implements ListCellRenderer {

    /**
     * Creates new form CommunityRows
     */
    public CommunityThreadRowView() {
        initComponents();
        setOpaque(true);
        spCommunityThreadRow.setBorder(null);
        spCommunityThreadRow.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        spCommunityThreadRow.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCommunityThreadRowTitle = new javax.swing.JLabel();
        spCommunityThreadRow = new javax.swing.JScrollPane();
        taCommunityThreadRowBody = new javax.swing.JTextArea();
        lblCommunityThreadDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        lblCommunityThreadRowTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblCommunityThreadRowTitle.setText("Lorem Ipsum Sim Dolor Amet");

        taCommunityThreadRowBody.setEditable(false);
        taCommunityThreadRowBody.setColumns(20);
        taCommunityThreadRowBody.setLineWrap(true);
        taCommunityThreadRowBody.setRows(5);
        taCommunityThreadRowBody.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. \nNam ac tristique nulla. Proin viverra elit quis est \neuismod malesuada. Cras in egestas arcu. . . ");
        taCommunityThreadRowBody.setWrapStyleWord(true);
        taCommunityThreadRowBody.setAutoscrolls(false);
        taCommunityThreadRowBody.setBorder(null);
        taCommunityThreadRowBody.setOpaque(false);
        spCommunityThreadRow.setViewportView(taCommunityThreadRowBody);

        lblCommunityThreadDate.setFont(new java.awt.Font("DejaVu Sans", 0, 8)); // NOI18N
        lblCommunityThreadDate.setText("Thursday, 11 August 2018");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCommunityThreadRowTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCommunityThreadDate))
                    .addComponent(spCommunityThreadRow, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommunityThreadDate)
                    .addComponent(lblCommunityThreadRowTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spCommunityThreadRow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCommunityThreadDate;
    private javax.swing.JLabel lblCommunityThreadRowTitle;
    private javax.swing.JScrollPane spCommunityThreadRow;
    private javax.swing.JTextArea taCommunityThreadRowBody;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        CommunityThreadRowModel model = (CommunityThreadRowModel) value;
        lblCommunityThreadDate.setText(model.getDate());
        lblCommunityThreadRowTitle.setText(model.getTitle());
        taCommunityThreadRowBody.setText(model.getBody());

        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }

        return this;
    }
}
