/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.hot_thread;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author maqielhm
 */
public class HotThreadRowView extends javax.swing.JPanel implements ListCellRenderer{

    /**
     * Creates new form HotThreadRows
     */
    public HotThreadRowView() {
        initComponents();
        setOpaque(true);
        spHotThreadRowBody.setBorder(null);
        spHotThreadRowBody.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        spHotThreadRowBody.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHotThreadRowImage = new javax.swing.JLabel();
        lblHotThreadRowName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHotThreadRowCommunity = new javax.swing.JLabel();
        lblHotThreadRowTitle = new javax.swing.JLabel();
        spHotThreadRowBody = new javax.swing.JScrollPane();
        taHotThreadRowBody = new javax.swing.JTextArea();
        lblHotThreadDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setName(""); // NOI18N
        setOpaque(false);

        lblHotThreadRowImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/ic_account_black_superSmall.png"))); // NOI18N

        lblHotThreadRowName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblHotThreadRowName.setText("John Doe");

        jLabel3.setText("has posted something at");

        lblHotThreadRowCommunity.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblHotThreadRowCommunity.setText("Lorem Ipsum");

        lblHotThreadRowTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblHotThreadRowTitle.setText("Lorem Ipsum Sim Dolor Amet");

        taHotThreadRowBody.setEditable(false);
        taHotThreadRowBody.setColumns(20);
        taHotThreadRowBody.setLineWrap(true);
        taHotThreadRowBody.setRows(5);
        taHotThreadRowBody.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. \nNam ac tristique nulla. Proin viverra elit quis est \neuismod malesuada. Cras in egestas arcu. . . ");
        taHotThreadRowBody.setWrapStyleWord(true);
        taHotThreadRowBody.setAutoscrolls(false);
        taHotThreadRowBody.setBorder(null);
        taHotThreadRowBody.setOpaque(false);
        spHotThreadRowBody.setViewportView(taHotThreadRowBody);

        lblHotThreadDate.setText("Thursday, 11 August 2018");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHotThreadDate)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHotThreadRowImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHotThreadRowTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHotThreadRowName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblHotThreadRowCommunity))
                                    .addComponent(spHotThreadRowBody, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHotThreadRowImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHotThreadRowName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHotThreadRowCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHotThreadRowTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spHotThreadRowBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHotThreadDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHotThreadDate;
    private javax.swing.JLabel lblHotThreadRowCommunity;
    private javax.swing.JLabel lblHotThreadRowImage;
    private javax.swing.JLabel lblHotThreadRowName;
    private javax.swing.JLabel lblHotThreadRowTitle;
    private javax.swing.JScrollPane spHotThreadRowBody;
    private javax.swing.JTextArea taHotThreadRowBody;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        HotThreadRowModel model = (HotThreadRowModel) value;
        
        lblHotThreadRowName.setText(model.getName());
        lblHotThreadDate.setText(model.getDate());
        lblHotThreadRowTitle.setText(model.getTitle());
        lblHotThreadRowCommunity.setText(model.getCommunity_name());
        taHotThreadRowBody.setText(model.getPreview());
        
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        return this;
    }
}
