/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.comment;

import home.member.*;
import home.community.*;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author maqielhm
 */
public class CommentRows extends javax.swing.JPanel implements ListCellRenderer {

    /**
     * Creates new form CommunityRows
     */
    public CommentRows() {
        initComponents();
        spCommentRowBody.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblCommentRowName = new javax.swing.JLabel();
        lblCommentRowAt = new javax.swing.JLabel();
        lblCommentRowDate = new javax.swing.JLabel();
        lblCommentRowPicture = new javax.swing.JLabel();
        spCommentRowBody = new javax.swing.JScrollPane();
        taCommentRowBody = new javax.swing.JTextArea();

        lblCommentRowName.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCommentRowName.setText("M Aqiel Hilman");

        lblCommentRowAt.setText("on");

        lblCommentRowDate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCommentRowDate.setText("Thursday, 12 Nov 2018");

        lblCommentRowPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/ic_account_black_superSmall.png"))); // NOI18N

        taCommentRowBody.setColumns(20);
        taCommentRowBody.setRows(5);
        spCommentRowBody.setViewportView(taCommentRowBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCommentRowPicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCommentRowName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCommentRowAt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCommentRowDate)
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spCommentRowBody)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCommentRowPicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCommentRowName)
                            .addComponent(lblCommentRowDate)
                            .addComponent(lblCommentRowAt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spCommentRowBody, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCommentRowAt;
    private javax.swing.JLabel lblCommentRowDate;
    private javax.swing.JLabel lblCommentRowName;
    private javax.swing.JLabel lblCommentRowPicture;
    private javax.swing.JScrollPane spCommentRowBody;
    private javax.swing.JTextArea taCommentRowBody;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        CommentModel model = (CommentModel) value;
        lblCommentRowDate.setText(model.getDate());
        lblCommentRowName.setText(model.getName());
        taCommentRowBody.setText(model.getBody());
        return this;
    }
}
